version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  # deploy:
  #   resources:
  #     limits:
  #       cpus: 0.50
  #       memory: 512M
  #       reservations:
  #         cpus: 0.25
  #         memory: 128M

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - /var/lib/postgresql/data/

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media
    depends_on:
      - db

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend